---
workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}

pipeline:
  build:
    image: golang:1.8.1
    commands:
    - make all
    - make static

  latest:
    image: docker:1.11
    environment:
      - AUTHOR=ukhomeofficedigital
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - NAME=keto-tokens
      - REGISTRY_USER=ukhomeofficedigital+keto_tokens
      - REPO=quay.io
    commands:
      - docker build -t ${REPO}/${AUTHOR}/${NAME}:latest .
      - docker login -u="${REGISTRY_USER}" -p=${DOCKER_PASSWORD} ${REPO}
    when:
      branch: master
      event: push

  deploy:
    image: docker:1.11
    environment:
      - AUTHOR=ukhomeofficedigital
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - NAME=keto-tokens
      - REGISTRY_USER=ukhomeofficedigital+keto_tokens
      - REPO=quay.io
    commands:
      - docker push ${REPO}/${AUTHOR}/${NAME}:${DRONE_TAG}
    when:
      event: tag

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"

